# Site settings
title: Design Resources
description: "Select websites, tools, and books for learning and working in design."
author: Jessica Paoli
locale: en-US

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

# Exclude from site build
exclude:
  - .DS_Store
  - node_modules
  - gulpfile.js
  - package.json
  - README.md

# Start a collection so we don't require dates in "_posts"
collections:
  resources:
    output: true
    permalink: /:collection/:name/
